{
 "title": "Docker overview with Cadvisor + docker state exporter + node exporter",
 "description": "Docker dashboard via Cadvisor + docker state exporter + node exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Docker ( Cadvisor )", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[15m])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Cached Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_cache{image!=\"\",container_label_org_label_schema_group=\"\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total[5m]))",
     "legendFormat": "written"
    },
    {
     "expr": "sum(irate(node_disk_io_time_seconds_total[5m]))",
     "legendFormat": "io time"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(container_last_seen) by (name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^.*\"}) / sum (machine_memory_bytes{kubernetes_io_hostname=~\"^.*\"}) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1m" }
   ]
  },
  {
   "title": "Containers Created",
   "type": "bargauge",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{image!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 29 },
   "targets": [
    {
     "expr": "count by(name) (count_over_time(container_last_seen{name=~\".+\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\",container_label_org_label_schema_group=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\",container_label_org_label_schema_group=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Unsued",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "machine_cpu_cores" }
     ]
    },
    {
     "title": "Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 3, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",kubernetes_io_hostname=~\"^.*\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 5, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{kubernetes_io_hostname=~\"^.*\"})"
      }
     ]
    },
    {
     "title": "Filesystem Usage by Container",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Filesystem Usage by Container",
     "type": "table",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes) by (name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}